version: '2.1'

services:
  datastore_emulator:
    image: quay.io/gumo/datastore-emulator:v241
    environment:
      DATASTORE_PROJECT_ID: gumo-task
      DATASTORE_LISTEN_ADDRESS: 0.0.0.0:8081
    ports:
      - "8081:8081"
    command: --no-store-on-disk

  datastore_emulator_test:
    image: quay.io/gumo/datastore-emulator:v241
    environment:
      DATASTORE_PROJECT_ID: gumo-task
      DATASTORE_LISTEN_ADDRESS: 0.0.0.0:8082
    ports:
      - "8082:8082"
    command: --no-store-on-disk --consistency=1
