version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.2
      - image: quay.io/gumo/datastore-emulator:v241
        command: --no-store-on-disk --consistency=1
        environment:
          GOOGLE_CLOUD_PROJECT: gumo-task
          DATASTORE_PROJECT_ID: gumo-task
          DATASTORE_LISTEN_ADDRESS: 0.0.0.0:8082

    environment:
      GOOGLE_APPLICATION_CREDENTIALS: credentials/service-account.json

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate

            pip install pip-tools
            make setup

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: prepare credentials
          command: |
            mkdir -p $(dirname $GOOGLE_APPLICATION_CREDENTIALS)
            echo $GOOGLE_SERVICE_ACCOUNT_EMPTY_ROLE_CREDENTIAL_CONTENT > $GOOGLE_APPLICATION_CREDENTIALS

      - run:
          name: check requirements.txt
          command: |
            . venv/bin/activate

            make build
            git diff --exit-code

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            make test

      - store_artifacts:
          path: test-reports
          destination: test-reports

      - store_test_results:
          path: test-reports
