version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.2
        environment:
          GOOGLE_CLOUD_PROJECT: gumo-task
          DATASTORE_EMULATOR_HOST: 127.0.0.1:8082
      - image: quay.io/gumo/datastore-emulator:v241
        command: --no-store-on-disk --consistency=1
        environment:
          DATASTORE_PROJECT_ID: gumo-task
          DATASTORE_LISTEN_ADDRESS: 0.0.0.0:8082

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - 20190628-00-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - 20190628-00-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate

            pip install pip-tools
            make setup

      - save_cache:
          paths:
            - ./venv
          key: 20190628-00-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            make test

      - store_artifacts:
          path: test-reports
          destination: test-reports

      - store_test_results:
          path: test-reports
